services:
  api:

    build: .
    

    container_name: osint_scanner_api
    

    ports:
      - "8000:8000"
      
    volumes:
      - .:/app

    env_file:
      - .env
      
    restart: unless-stopped

